server:
   port: 8084
spring:
   application:
      name: stockmarket-price-service
   profiles:
      active: default
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/stockmarket?useUnicode=true&characterEncoding=utf-8
      username: root
      password: passw0rd
   jpa:
      hibernate:
         database-platform: org.hibernate.dialect.MySQLDialect
         ddl-auto: update
         show-sql: true
   jackson:
      time-zone: UTC
   servlet:
      multipart:
         enabled: true
         max-file-size: 20MB
         max-request-size: 20MB
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

file:
   upload-dir: /Users/Charles/Workspace/temp/

eureka:
   instance:
      preferIpAddress: true
      client: 
         registerWithEureka: true
         fetchRegistry: true
         serviceUrl: 
            defaultZone: http://localhost:8761/eureka/
