server:
   port: 8761
eureka:
   instance:
      lease-renewal-interval-in-seconds: 5
      lease-expiration-duration-in-seconds: 15
   server:
      enable-self-preservation: false
      response-cache-auto-expiration-in-seconds: 60
      eviction-interval-timer-in-ms: 10000
   client:
      registerWithEureka: false
      fetchRegistry: false
      serviceUrl: 
         defaultZone: http://localhost:8761/eureka/
